#!/bin/bash

################################################################################
#                                   INIT                                       #
################################################################################
RPMEASY=$HOME/git/bash/rpm-scripts/rpmeasy-functions.sh
if [ -f "$RPMEASY" ]; then
        . "$RPMEASY"
fi

prepare_env "blender-trunk" \
            "$HOME/git/bash/rpm-scripts/blender/blender-trunk-skel" \
            "$HOME/git/localrepo"

################################################################################
#                                   DOWNLOAD                                   #
################################################################################
if [[ ! -z "$FILE" ]] && [[ "$FILE" = *blender*.@(tar.bz2|tar.gz) ]]; then
    echo "A file was specified"
else
    URL="http://builder.blender.org/download/"
    wget -q $URL
    FILE=`egrep  ">blender.*glibc219-x86_64.tar.bz2" -o index.html  | cut -c 2-`
    wget $URL/$FILE -P $TEMP/src
fi

################################################################################
#                                   SKELETON                                   #
################################################################################
# copy rpm skeleton to $TEMP
cp -rf $SKEL .
# extract the tar.bz2 then move inside the skeleton
tar -xjf $FILE -C .

# fix all the things
mv `basename -s .tar.bz2 $FILE`  $PKG_NAME-skel/opt/blender

################################################################################
#                                   SPEC                                       #
################################################################################
# generate package info
echo "Summary: 3D modeling, animation, rendering and post-production
Vendor: Blender Foundation
Packager: fabiolbr
License: GPLv2
Group: Applications/Multimedia
URL: http://www.blender.org
Description: Blender is the essential software solution you need for 3D, from modeling,animation, rendering and post-production to interactive creation and playback.
#Requires: google-droid-sans-fonts python3-numpy python3-requests" > pkg.in

prepare_build python_off

# fix conflicts
sed '/^%dir \/usr\/bin$/d' -i *files.txt
sed '/%attr/s/.*/&"/' -i *files.txt                    #add " at the end of every line with attr
sed 's/,-,-) /,-,-) "/g' -i *files.txt                 #add " before the file name for every attr line
sed 's/%attr(,-,-)/%attr(644,-,-)/g' -i *files.txt     #fix permissions

################################################################################
#                                BUILD + INSTALL                               #
################################################################################
# build rpm
VERSION=`echo $FILE | cut -d '-' -f 2`
RELEASE=`echo $FILE | cut -d '-' -f 3`
#ARCH=`echo $FILE | cut -d '-' -f 6 | cut -d '.' -f 1`
build_rpm $VERSION $RELEASE

# move old tar.gz, tar.bz2 or rpm in old folder #TODO: implement inside rpmeasy a new var for "OLD"
mv $DEST/blender*.{tar.bz2,tar.gz,rpm} $DEST/old 2> /dev/null

install_rpm
