#!/bin/bash

################################################################################
#                                   INIT                                       #
################################################################################
RPMEASY=$HOME/git/bash/rpm-scripts/rpmeasy-functions.sh
if [ -f "$RPMEASY" ]; then
        . "$RPMEASY"
fi

prepare_env "blender-trunk" \
            "$HOME/git/bash/rpm-scripts/blender/blender-trunk-skel" \
            "$HOME/git/localrepo"

# move old rpm, tar.bz2 in old folder
mv $DEST/blender*.{tar.bz2,rpm} $DEST/old 2> /dev/null

################################################################################
#                                   DOWNLOAD                                   #
################################################################################
URL="http://builder.blender.org/download/"

# download only if there isn't a blender tar.bz2 as parameter
if [[ "$1" = *blender*.tar.bz2 ]]; then
    FILE="$1"
else
    wget -q $URL
    FILE=`egrep  ">blender.*glibc219-x86_64.tar.bz2" -o index.html  | cut -c 2-`
    wget $URL/$FILE
fi

################################################################################
#                                   SKELETON                                   #
################################################################################
# copy rpm skeleton to $TEMP
cp -rf $SKEL .
# extract the tar.gz then move inside the skeleton
tar -xjf $FILE -C .

# fix all the things
mv `basename -s .tar.bz2 $FILE`  $PKG_NAME-skel/opt/blender

################################################################################
#                                   SPEC                                       #
################################################################################
# generate package info
echo "Summary: 3D modeling, animation, rendering and post-production
Vendor: Blender Foundation
Packager: fabiolbr
License: GPLv2
Group: Applications/Multimedia
URL: http://www.blender.org
Description: Blender is the essential software solution you need for 3D, from modeling,animation, rendering and post-production to interactive creation and playback.
#Requires: google-droid-sans-fonts python3-numpy python3-requests" > pkg.in

prepare_build python

# fix conflicts
sed '/^%dir \/usr\/bin$/d' -i *files.txt

################################################################################
#                                BUILD + INSTALL                               #
################################################################################
# build rpm
VERSION=`echo $FILE | cut -d '-' -f 2`
RELEASE=`echo $FILE | cut -d '-' -f 3`
#ARCH=`echo $FILE | cut -d '-' -f 6 | cut -d '.' -f 1`
build_rpm $VERSION $RELEASE

install_rpm
