#!/bin/bash

function checkExec () {
    if [ -z `which $1` ]; then
        echo "$1 not present"
        exit
    fi
}

checkExec "rpmwand"
checkExec "xsel"

# variables
PKG_NAME=firefox-trunk
BRANCH=mozilla-central
SKEL=$HOME/git/bash/update-firefox/$PKG_NAME-skel  #source of skeleton and script
DEST=$HOME/git/firefox-desktop  #destination of rpm and deb
TEMP=/tmp/$PKG_NAME-rpm
URL="https://launchpad.net/~ubuntu-mozilla-daily/+archive/ppa/+packages"

# download firefox to $DEST
mkdir -p $DEST && mkdir -p $TEMP

# move old deb\rpm in old folder. TODO: aggiungere un comando che vede la data dei file e eventualmente li cancella
mv $DEST/*.{deb,rpm} $DEST/old 2> /dev/null

# download only if there isn't a firefox-trunk deb package as parameter
if [[ "$1" = *firefox-trunk*.deb ]]; then
    FILE="$1"
else 
    #open the mozilla daily link. You need to copy the deb link. It will be used later
    notify-send -i firefox-trunk "Copy latest firefox-trunk deb link and then close firefox"
    killall firefox | sleep 2 && epiphany $URL
    #wget `gpaste get 0` -P $DEST
    wget `xsel -b` -P $DEST
    FILE=`ls $DEST/*.deb`
fi

# copy rpm skeleton to $TEMP
cp -rf $SKEL $TEMP
# extract the deb then move inside the skeleton
file-roller --extract-to=$TEMP "$FILE"
tar xf $TEMP/data.tar.xz -C $TEMP

# fix all the things
mv $TEMP/usr/lib/firefox-trunk $TEMP/$PKG_NAME-skel/usr/lib64/
mv $TEMP/usr/lib/firefox-trunk-addons $TEMP/$PKG_NAME-skel/usr/lib64/
mv $TEMP/usr/bin/firefox-trunk $TEMP/$PKG_NAME-skel/usr/bin/
rm $TEMP/$PKG_NAME-skel/usr/lib64/firefox-trunk/hyphenation
rm $TEMP/$PKG_NAME-skel/usr/lib64/firefox-trunk/browser/defaults/preferences/syspref.js
rm $TEMP/$PKG_NAME-skel/usr/lib64/firefox-trunk/browser/plugins
cp -P $SKEL/../extra-fedora/dictionaries $TEMP/$PKG_NAME-skel/usr/lib64/firefox-trunk/
cp -P $SKEL/../extra-fedora/firefox-trunk $TEMP/$PKG_NAME-skel/usr/bin/
cp -P $SKEL/../extra-fedora/plugins $TEMP/$PKG_NAME-skel/usr/lib64/firefox-trunk/browser/


# on fedora we use lib64
sed -i 's/usr\/lib/usr\/lib64/g' "$TEMP/$PKG_NAME-skel/usr/lib64/firefox-trunk/firefox.sh"

# create the default prefs that in ubuntu version is not present
echo -e "pref(\"app.update.auto\",                     false);
pref(\"app.update.enabled\",                  false);
pref(\"app.update.autoInstallEnabled\",       false);
pref(\"general.smoothScroll\",                true);
pref(\"intl.locale.matchOS\",                 true);
pref(\"toolkit.storage.synchronous\",         0);
pref(\"toolkit.networkmanager.disable\",      false);
pref(\"offline.autoDetect\",                  true);
pref(\"browser.backspace_action\",            2);
pref(\"browser.display.use_system_colors\",   true);
pref(\"browser.download.folderList\",         1);
pref(\"browser.link.open_external\",          3);
pref(\"browser.shell.checkDefaultBrowser\",   false);
pref(\"network.manage-offline-status\",       true);
pref(\"dom.ipc.plugins.enabled.nswrapper*\",  false);
pref(\"extensions.shownSelectionUI\",         true);
pref(\"gfx.color_management.enablev4\",       true);
pref(\"ui.SpellCheckerUnderlineStyle\",       1);
pref(\"startup.homepage_override_url\",       \"\");
pref(\"browser.startup.homepage\",            \"data:text/plain,browser.startup.homepage=about:newtab\");
pref(\"browser.newtabpage.pinned\",           '[{\"url\":\"http://start.fedoraproject.org/\",\"title\":\"Fedora Project - Start Page\"}]');" > $TEMP/$PKG_NAME-skel/usr/lib64/firefox-trunk/browser/defaults/preferences/firefox-redhat-default-prefs.js


#initialize and edit *spec.in
cd $TEMP && rpmwand initspec $PKG_NAME
sed -i 's/Summary: TODO. PLEASE EDIT ME!/Summary: Safe and easy web browser from Mozilla/g'  "$PKG_NAME".spec.in
sed -i 's/Vendor: TODO. PLEASE EDIT ME!/Vendor: Mozilla/g'  "$PKG_NAME".spec.in
sed -i 's/Packager: TODO. PLEASE EDIT ME!/Packager: fabiolbr/g'  "$PKG_NAME".spec.in
sed -i 's/License: TODO. PLEASE EDIT ME!/License: GPL v3/g'  "$PKG_NAME".spec.in
sed -i 's/Group: TODO. PLEASE EDIT ME!/Group: Applications\/Internet/g'  "$PKG_NAME".spec.in
sed -i 's/URL: http:\/\/TODO.example.com\//URL: http:\/\/nightly.mozilla.org/g'  "$PKG_NAME".spec.in

# editing *files.txt and fix symbolics links and other conflicts
rpmwand files $PKG_NAME
sed '/^%dir \/usr\/bin$/d' -i "$PKG_NAME"-files.txt
sed '/^%dir \/usr\/lib64$/d' -i "$PKG_NAME"-files.txt
sed -i 's/%dir \/usr\/lib64\/firefox-trunk\/dictionaries/%attr(777,-,-) \/usr\/lib64\/firefox-trunk\/dictionaries/g' "$PKG_NAME"-files.txt
sed -i 's/%dir \/usr\/lib64\/firefox-trunk\/distribution\/extensions/%attr(777,-,-) \/usr\/lib64\/firefox-trunk\/distribution\/extensions/g' "$PKG_NAME"-files.txt
sed -i 's/%dir \/usr\/lib64\/firefox-trunk\/browser\/searchplugins/%attr(777,-,-) \/usr\/lib64\/firefox-trunk\/browser\/searchplugins/g' "$PKG_NAME"-files.txt
sed -i 's/%dir \/usr\/lib64\/firefox-trunk\/browser\/plugins/%attr(777,-,-) \/usr\/lib64\/firefox-trunk\/browser\/plugins/g' "$PKG_NAME"-files.txt
sed -i 's/%dir \/usr\/lib64\/firefox-trunk\/browser\/extensions/%attr(777,-,-) \/usr\/lib64\/firefox-trunk\/browser\/extensions/g' "$PKG_NAME"-files.txt

# build rpm
VERSION=`cat "$PKG_NAME"-skel/usr/lib64/firefox-trunk/application.ini | grep Version | cut -d '=' -f 2 | tail -n 1`
RELEASE=`cat "$PKG_NAME"-skel/usr/lib64/firefox-trunk/application.ini | grep BuildID | cut -d '=' -f 2`
HOME=$TEMP #this force to build inside $TEMP and not $HOME
rpmwand build $PKG_NAME $VERSION $RELEASE x86_64

# erase the old package (to avoid some misc files around the system...)
sudo dnf -y erase $PKG_NAME

# install
sudo dnf -y install $TEMP/RPMS/x86_64/$PKG_NAME-$VERSION-$RELEASE.x86_64.rpm

# save the rpm
cp $TEMP/RPMS/x86_64/$PKG_NAME-$VERSION-$RELEASE.x86_64.rpm $DEST/

# cleanup
#rm -rf $HOME/rpmbuild
rm -rf $TEMP

