#!/bin/bash
# find, recursively, files with a specified text in the name and rename the file without the text
FILES="/tmp/list.txt"

name="Clean Filenames"

opt1="DDLValley.rocks_"
opt2="TwoDDL.eu_"
opt3="Micromkv.com - "
opt4="Micromkv.com -_"
optn="Custom String"

op=`zenity --name="$name" --hide-header --height=150 --list --radiolist --title="$name" --text 'Select text to replace:' --column '' --column 'Text' TRUE "$opt1" FALSE "$opt2" FALSE "$opt3" FALSE "$opt4" FALSE "$optn"`
echo "Chosen option: "$op

case "$op" in
    $opt1)
    TEXT=$opt1
    ;;
    $opt2)
    TEXT=$opt2
    ;;
    $opt3)
    TEXT="$opt3"
    ;;
    $opt4)
    TEXT="$opt4"
    ;;
    $optn)
    TEXT=`zenity --name="$name" --entry --title="Custom Text to Replace" --text="Enter the text" --entry-text=XXXXXX`
    ;;
    *)
    # no selection
    exit
esac


DIR=`zenity --file-selection --directory`
cd "$DIR"

# text in any part of the filename
find . -name "*$TEXT*" > $FILES

# text only at the beginning
#find . -name "$TEXT"* > $FILES

while read FILE  ; do
        NEWFILE=`echo "$FILE" | sed s/"$TEXT"//g `
        echo "Renaming  "$FILE"    TO     "$NEWFILE""
        mv "$FILE" "$NEWFILE"
done < $FILES

rm $FILES


notify-send -i "bleachbit" "CLEANED: $DIR"
