#!/bin/sh
# take a binary app(must be gtk3) as parameter and it set the dark theme
# "$@" take all the arguments passed to this script
#
# gtk-application-prefer-dark-theme=0     #normal theme
# gtk-application-prefer-dark-theme=1	  #force dark theme

# modalità supportata di default. problema: metacity non viene temizzato
# with gtk 3.16(o 3.18?) it won't be a problem anymore
#THEME=`dconf read /org/gnome/shell/extensions/user-theme/name  | sed -r "s/'//g"`
#GTK_THEME=$THEME:dark "$@" &

GTK="$HOME/.config/gtk-3.0/settings.ini"

if [[ -z "$@" ]]; then
    echo "Usage: darken <command> [<arguments>]"
    exit
fi

#check presence for dark theme setting
SETTING=`cat $GTK | grep gtk-application-prefer-dark-theme`

#force the dark theme
if [ -z "$SETTING" ]; then
    echo "gtk-application-prefer-dark-theme=1" >> $GTK
else
    sed -i 's/dark-theme=0/dark-theme=1/g' $GTK
fi

#open the app and all its arguments
"$@" &

#take a knee
sleep 1

#restore normal theme
sed -i 's/dark-theme=1/dark-theme=0/g' $GTK
