#!/bin/bash
# better alternative to gksu\gksudo integrated to gnome-shell
if [ -z "$@" ]; then
    echo "Usage: gksu <command> [<arguments>]"
    exit
fi
pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY "$@"
