#!/bin/bash
# NAME: hungry-nvidia-ram
# DESCRIPTION: send a gnome-shell notification if a the used vga ram is 
# more than 700Mb. If blender is running only when more than 1500Mb
# NEED: zenity, nvidia-smi (nvidia-settings)
#
# USAGE: set it with a keyboard shortcut or with cron. 
# $HOME/YOURPATH/hungyVGAram

# fix execution notify-send from cron. (problem since gnome3.8) 
#export $(cat /proc/$(pgrep -u `whoami` ^gnome-shell$)/environ | grep -z DBUS_SESSION_BUS_ADDRESS)

pidBlender=`pidof blender | cut -d ' ' -f 1`

if [ -z "$pidBlender" ]
then
	warningMb=750
else
	warningMb=1000
fi

memory=`nvidia-smi | grep MiB`
usedRam=`echo $memory | cut -d ' ' -f 9 | cut -d 'M' -f 1`
totalRam=`echo $memory | cut -d ' ' -f 11 | cut -d 'M' -f 1`

if (( usedRam >= warningMb ))
then
	notify-send "Nvidia ram used is $usedRam Mb of $totalRam Mb"
fi

exit 0
