#!/bin/bash
# NAME: hungry-process
# DESCRIPTION: send a gnome-shell notification if a process is using too much memory
# NEED: zenity
#
# USAGE: set it with a keyboard shortcut or with cron. 
# Pass two parameters:  process's name and for how much Mb you want a notification
# $HOME/YOURPATH/hungry-process PROCESSNAME MB

# fix problem with gnome 3.8\3.10 that not send libnotify notifications is script used with cron
#export $(cat /proc/$(pgrep -u `whoami` ^gnome-shell$)/environ | grep -z DBUS_SESSION_BUS_ADDRESS)

process=$1
maxmem=$2

# check if parameter number is ok
if (($# < 2))
then
	echo "Usage $0 processName maxmem "
	exit 1
fi

# check if $process is running
#pid=`ps -A | grep $process`
pid=`pidof $process | cut -d ' ' -f 1`
if [ -z "$pid" ]; then
	echo $process is not running
	exit 2
fi

# check if $maxmem is a number
if ! [[ "$maxmem" =~ ^[0-9]+$ ]]; then
   exec >&2; echo "error: maxMem Not a number";
   exit 1
fi

# get line of top. -bn is the only parameter to make it work on cron
#line=`top -bn 1 -p$pid | grep $process`
# get memory used by $process
#kbmem=`echo $line | cut -d ' ' -f 6`

# get Proportional Set Size (Pss) instead of Resident Set Size (Rss)
kbmem=`cat /proc/$pid/smaps | grep -e "^Pss:" | awk '{print $2}'| paste -sd+ | bc `

#convert from Kb to Mb
let mem=${kbmem/,}/1024

#if memory more $2 then send notification
if (( $mem > $maxmem )); then
	notify-send "$process is using $mem Mb"
fi

exit 0
