#!/bin/bash
# NAME:
# DESCRIPTION:
# NEED:
# USAGE:

# fix execution notify-send from cron. (problem since gnome3.8) 
#export $(cat /proc/$(pgrep -u `whoami` ^gnome-shell$)/environ | grep -z DBUS_SESSION_BUS_ADDRESS)

#alternative command where c39-40 stand for "from col 39 to 40"
#nvidia-smi -q -d TEMPERATURE | grep Gpu | cut -c39-40

function showTemp () {
	notify-send -i $icon "GPU		Temperature: $temp °C		Fan Speed:  $fanspeed"
}

temp=`nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader`
fanspeed=`nvidia-smi | grep % | cut -c2-5`
warning=55
normal=45

if (( temp > warning )); then
	icon="dialog-warning"
else
	icon="nvidia-settings"
fi

if [ "$1" == "-f" ] || (( temp > normal)); then
	showTemp
fi
