#!/bin/bash
# for a more complete list of codecs open openshot via bash
# or see them here http://libav.org/avconv.html  full of options and parameters for avconv

#A few formats examples: avi, matroska, mp4, ogg, webm
#A few video codecs examples: libx264, libxvid, libtheora, mpeg4, flv, 
#A few audio codecs examples: libmp3lame, libvorbis, vorbis, aac, ac3, flac, 


#OPEN FILE 
#TODO: fix when there is more then just one "dot" other than for the extension
INPUT=`zenity --title="Video Converter" --file-selection`
NAME=`echo $INPUT | cut -d '.' -f 1`
EXT=`echo $INPUT | cut -d '.' -f 2`


#DEFAULT SETTINGS
zenity --question --text="Use default settings? video: mp4|libx264@512kb/s,  audio: copy"
if [[ $? == 0 ]] ; then
    #true
    EXT_OUT="mp4"
    CODEC_VID=libx264
    BITRATE_VID=512
    VIDEO="-c:v $CODEC_VID -b:v "$BITRATE_VID"k"
    AUDIO="-c:a copy"
else
    #false
    #FORMAT
    EXT_OUT=`zenity --entry --title="Format(container\extensions)" --text="Enter the format" --entry-text=mp4`

    #AUDIO
    zenity --question --text="Skip audio transcoding?"
    if [[ $? == 0 ]] ; then
        #true
        AUDIO="-c:a copy"
    else
        #false
        CODEC_AUD=`zenity --entry --title="Audio Codec" --text="Enter Audio Codec" --entry-text=libmp3lame`
        BITRATE_AUD=`zenity --entry --title="Audio Bitrate" --text="Enter # in kb/s" --entry-text=128`
        AUDIO="-c:a $CODEC_AUD -b:a "$BITRATE_AUD"k"
    fi

    #VIDEO
    CODEC_VID=`zenity --entry --title="Video Codec" --text="Enter Video Codec" --entry-text=libx264`
    BITRATE_VID=`zenity --entry --title="Video Bitrate" --text="Enter # in kb/s" --entry-text=512`
    VIDEO="-c:v $CODEC_VID -b:v "$BITRATE_VID"k"
fi



#OUTPUT
avconv -i "$NAME.$EXT" -f $EXT_OUT $VIDEO $AUDIO "$NAME.$EXT_OUT"
#TODO: ask if I want to play the file(to check it) and then ask to remove the old one
notify-send -i "avidemux" "Converted: $NAME.$EXT_OUT"
