#!/bin/bash
# for a more complete list of codecs open openshot via bash
# or see them here http://libav.org/avconv.html  full of options and parameters for avconv

# A few formats examples: avi, matroska, mp4, ogg, webm
# A few video codecs examples: libx264, libxvid, libtheora, mpeg4, flv, 
# A few audio codecs examples: libmp3lame, libvorbis, vorbis, aac, ac3, flac, 


# open file
INPUT=`zenity --title="Video Converter" --file-selection`

# array of extensions
EXT=(mp4 avi mkv flv webm m4v matroska mpeg)

# check extension,  split name\extension
for EXT in "${EXT[@]}"
do
    if [[ "$INPUT" =~ .$EXT ]]; then
        NAME=`echo "$INPUT" | sed s/.$EXT//g `
        break;
    fi
done

if [ -z "$NAME" ]; then
    notify-send -i "avidemux" "Not a video file"
    exit;
fi

# default settings
zenity --question --text="Use default settings? video: mp4|libx264@512kb/s,  audio: copy"
if [[ $? == 0 ]] ; then
    FORMAT="mp4"
    CODEC_VID=libx264
    BITRATE_VID=512
    VIDEO="-c:v $CODEC_VID -b:v "$BITRATE_VID"k"
    AUDIO="-c:a copy"
else
    # format & ext_out
    FORMAT=`zenity --entry --title="Format(container\extensions)" --text="Enter the format" --entry-text=mp4`

    # audio
    zenity --question --text="Skip audio transcoding?"
    if [[ $? == 0 ]] ; then
        AUDIO="-c:a copy"
    else
        CODEC_AUD=`zenity --entry --title="Audio Codec" --text="Enter Audio Codec" --entry-text=libmp3lame`
        BITRATE_AUD=`zenity --entry --title="Audio Bitrate" --text="Enter # in kb/s" --entry-text=128`
        AUDIO="-c:a $CODEC_AUD -b:a "$BITRATE_AUD"k"
    fi

    # video
    CODEC_VID=`zenity --entry --title="Video Codec" --text="Enter Video Codec" --entry-text=libx264`
    BITRATE_VID=`zenity --entry --title="Video Bitrate" --text="Enter # in kb/s" --entry-text=512`
    VIDEO="-c:v $CODEC_VID -b:v "$BITRATE_VID"k"
fi

EXT_OUT=$FORMAT
if [[ "$FORMAT" == "matroska" ]]; then
    EXT_OUT="mkv"
fi

# output
avconv -i "$NAME.$EXT" -f $FORMAT $VIDEO $AUDIO "$NAME.$EXT_OUT"
# TODO: ask if I want to play the file(to check it) and then ask to remove the old one
notify-send -i "avidemux" "Converted: $NAME.$EXT_OUT"
