#!/bin/bash
if [[ -z $BACKUP || -z $PKGSYS ]]; then
    exit 1
fi

FOLDER_DST="$BACKUP/system"

cd $HOME

#PACKAGES LIST
if [ $PKGSYS = "apt" ]; then
    dpkg --get-selections > $FOLDER_DST/deb_packages.list
fi 

if [ $PKGSYS = "yum" ]; then
    yum list installed > $FOLDER_DST/yum_packages_installed.list
    yum list extras > $FOLDER_DST/yum_packages_extras.list
fi


#BACKUP OTHER FOLDERS
sudo tar -pcvzf etc.tar.gz /etc
sudo tar -pcvzf ftp.tar.gz /home/ftp

#MOVE TO EXTERNAL HDD
mv etc.tar.gz $FOLDER_DST/
sudo mv ftp.tar.gz $FOLDER_DST/
