#!/bin/bash
if [[ -z $BACKUP || -z $PKGSYS ]]; then
    exit 1
fi

FOLDER_DST="$BACKUP/system"

#######################################
#                 MISC
#######################################

echo -e "\nBacking up $USER's dconf settings"
dconf dump / > "$FOLDER_DST/dconf_dump.txt"


echo -e "\nBacking up packages list..."
if [ $PKGSYS == "apt" ]; then
    dpkg --get-selections > "$FOLDER_DST/deb_packages.list"
fi

if [ $PKGSYS == "dnf" ]; then
    sudo dnf list installed >  "$FOLDER_DST/dnf_packages_installed.list"
    sudo dnf list extras > "$FOLDER_DST/dnf_packages_extras.list"
fi


#######################################
#    BACKUP OTHER FOLDERS  [tar.gz]
#######################################

echo -e "\nBacking up /etc" && sleep 2

sudo tar -pcvzf "$FOLDER_DST/etc.tar.gz" "/etc"
