#!/bin/bash
if [[ -z $BACKUP || -z $PKGSYS ]]; then
    exit 1
fi

FOLDER_DST="$BACKUP/system"

#######################################
#                 MISC
#######################################

echo -e "\nBacking up $USER's dconf settings"
dconf dump / > $FOLDER_DST/settings.txt


echo -e "\nBacking up packages list..."
if [ $PKGSYS = "apt" ]; then
    dpkg --get-selections > $FOLDER_DST/deb_packages.list
fi 

if [ $PKGSYS = "yum" ]; then
    yum list installed > $FOLDER_DST/yum_packages_installed.list
    yum list extras > $FOLDER_DST/yum_packages_extras.list
fi


#######################################
#    BACKUP OTHER FOLDERS  [tar.gz]
#######################################

echo -e "\nBacking up /etc & /home/ftp" && sleep 2

sudo tar -pcvzf "$FOLDER_DST/etc.tar.gz" "/etc"
sudo tar -pcvzf "$FOLDER_DST/ftp.tar.gz" "/home/ftp"
