#!/bin/bash
# This script take a blender new release folder, cleanup link files\folder and then recreate them
# To be sure it checks if blender and blenderplayer are present in this folder
#
# requirements: zenity
# more info on zenity: http://help.gnome.org/users/zenity/3.6/
#select blender folder

#TODO: implement parsing of $@ to choose interface: terminal \ gui

folder=`zenity --file-selection --directory --title="Select blender folder" --filename="~/"`
echo "Folder="$folder

blender="$folder/blender"
blenderplayer="$folder/blenderplayer"
blenderthumbnailer="$folder/blender-thumbnailer.py"

#check if blender and blenderplayer are present in $folder
if  [[ -e "$blender"  && -e "$blenderplayer" ]]; then
     echo -e "\nFOUND: blender & blenderplayer \n"
else
     notify-send -i "error" "ERROR: blender & blenderplayer not found. Make sure you have the correct folder"
     exit
fi

if [[ $USER = "root" ]]; then
    path="/usr"
else
    path="$HOME/.local"
fi

#cleanup symbolic links
rm "$path/bin/blender" 2> /dev/null
rm "$path/bin/blenderplayer" 2> /dev/null
rm "$path/bin/blender-thumbnailer.py" 2> /dev/null

#create symbolic links
ln -s $blender "$path/bin/blender"
ln -s $blenderplayer "$path/bin/blenderplayer"
ln -s $blenderthumbnailer "$path/bin/blender-thumbnailer.py"

if [[ $USER = "root" ]]; then
    path="/usr/share"
else
    path="$HOME/.local/share"
fi

#check if blender.desktop exist
if [[ ! -e "$path/applications/blender.desktop" ]]; then
echo "[Desktop Entry]
Name=Blender
GenericName=3D modeller
Comment=3D modeling, animation, rendering and post-production
Exec=blender
Icon=blender
Terminal=false
Type=Application
Categories=Graphics;3DGraphics;
MimeType=application/x-blender;" > $path/applications/blender.desktop
fi

#check if thumbnailer entry exist
if [[ ! -e "$path/thumbnailers/blender.thumbnailer" ]]; then
echo "[Thumbnailer Entry]
TryExec=blender-thumbnailer.py
Exec=blender-thumbnailer.py %u %o
MimeType=application/x-blender;" > $path/thumbnailers/blender.thumbnailer
fi

#zenity --notification --window-icon="info"  --text="Aggiornati link blender"
notify-send -i blender "Aggiornati link blender"

zenity --question --text="Do you want to open blender?"
answer=$?
if [ "$answer" -eq "0" ]; then
     #TODO: how to close the terminal but still open blender? 
     blender
fi
exit
