#!/bin/bash
#requirements:  rsync 

#INITALIZATION
export SCRIPTS=$HOME/coding/bash/backup

#ubuntu or fedora?
if [ ! -z `which apt 2> /dev/null` ]; then           # probably using ubuntu\debian\mint
    MOUNT=/media
    PKGSYS=apt
elif [ ! -z `which yum 2> /dev/null` ]; then      # probably using fedora\redhat
    MOUNT=/run/media
    PKGSYS=yum
else
    exit 1
fi

export PKGSYS

#rsync missing?
if [ -z `which rsync 2> /dev/null` ]; then             # rsync not installed
        sudo $PKGSYS install rsync
fi

export BASE_BKP=$MOUNT/$USERNAME/Backup

#GO TO BASE PATH OF SCRIPTS
cd $SCRIPTS

#MEDIA
echo ""
echo "##### MEDIA  ##### "
echo ""
echo -n "Start backing up media? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./000-media/000-media-start
fi


#HOME
echo ""
echo "##### HOME  ##### "
echo ""
echo -n "Start backing up home? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./100-home/100-home-start
fi


#SYSTEM
echo ""
echo "##### SYSTEM  ##### "
echo ""
echo -n "Start backing up system? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./200-system/200-system-start
fi


#WIN
echo ""
echo "##### WINDOWS  ##### "
echo ""
echo -n "Start backing up win? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./300-win/300-win-start
fi
