#!/bin/bash

FILE=~/.local/share/applications/nettygear.desktop

if [[ ! -e "$FILE" ]]; then
echo "[Desktop Entry]
Name=Netty Gear
GenericName=Netty Gear
Comment=Manage the Netgear_DG834G
Exec=nettygear -g -l
Icon=nettygear
Terminal=false
Type=Application
Categories=Application;Network;
" > $FILE
chmod +x $FILE
fi

echo "App Installed in: $FILE"
