#!/bin/bash

if [[ -z $BACKUP || -z $SCRIPTS ]]; then
    exit 1
fi

# Source essential functions
if [ -f "functions.sh" ]; then
    . "functions.sh"
fi

#######################################
#                 RSYNC
#######################################

#go to rsync scripts
cd $SCRIPTS/100-home

startScript "$HOME/.*" "./101-home-hidden"
startScript "$HOME/android" "./102-home-android"
startScript "$HOME/cgi" "./103-home-cgi"
startScript "$HOME/downloads/sw-linux" "./104-home-downloads-sw-linux"
startScript "$HOME/downloads/operating-systems" "./105-home-downloads-operating-systems"
startScript "$HOME/videos" "./106-home-videos"
startScript "$HOME/guitar" "./107-home-guitar"

#######################################
#    BACKUP OTHER FOLDERS  [tar.gz]
#######################################

BKP_DST="$BACKUP/home"

DIRS=(coding documents git workspace)
for DIR in "${DIRS[@]}"
do
    backupFolder "$HOME/$DIR" "$BKP_DST" "$DIR"
done

backupFolder "/home/symlinks" "$BKP_DST" "symlinks"
