#!/bin/bash

if [[ -z $BACKUP ]]; then
	exit 1
fi

# Source essential functions
if [ -f "../functions.sh" ]; then
	. "../functions.sh"
fi

BKP_DST=$BACKUP/home

# hidden files
echo -ne "\n$HOME/.* ? [y/n]: "
read answer

if [[ $answer == "y" ]]; then
	#EXCLUDE="--exclude=.cache/rsync --exclude=.cache/mozilla
	#		 \--exclude=.cache/epiphany-* --exclude=*.cache/google-chrome*"

	EXCLUDE="--exclude=.cache/epiphany-* --exclude=.cache/thumbnails --exclude=.mozilla --exclude=.local/share/flatpak"
	BKP_NAME=dot.home

	# clean trash
	gio trash  --empty

	# backup
	(cd $HOME && find . -maxdepth 1 -name ".?*" -exec tar pcvzf "$BKP_DST/$BKP_NAME".tar.gz $EXCLUDE {} +)
fi

# symbolic links and single folders
DIRS=(.mozilla .android .gradle)
for DIR in "${DIRS[@]}"
do
	if [ ! -h "$HOME/$DIR" ]; then
		backupFolder "$HOME/$DIR" "$BKP_DST" "dot$DIR"
	else
		backupFolder "`readlink -q $HOME/$DIR`" "$BKP_DST" "dot$DIR"
	fi
done

