#!/bin/bash

if [[ -z $BACKUP ]]; then
    exit 1
fi

# Source essential functions
if [ -f "../functions.sh" ]; then
    . "../functions.sh"
fi


EXCLUDE="--exclude=*/.cache/rsync --exclude=*/.cache/mozilla*
         \--exclude=*/.cache/epiphany* --exclude=*/.cache/google-chrome
         \--exclude=*/.nv"

DIR_SRC=$HOME
BKP_DST=$BACKUP/home
BKP_NAME=hidden_home

#clean trash
#rm -rf $HOME/.local/share/Trash
gvfs-trash  --empty

find $HOME -maxdepth 1 -name ".?*" -exec tar pcvzf "$BKP_DST/$BKP_NAME".tar.gz $EXCLUDE {} +
