#!/bin/bash

if [[ -z $BACKUP ]]; then
	exit 1
fi

#rsync parameters
LOG_FILE="$HOME/.cache/rsync/106-home-guitar.log"
PARAMS=" -r -t -p -o -g -v --progress --delete -l -s -h --stats --log-file=$LOG_FILE"
EXCLUDE=""
SRC="$HOME/guitar/"
DST="$BACKUP/home/guitar/"
#NOTE:  the last exclude is basically the name of the dst folder. It's necessary only if dst folder is inside the src folder

#rsynch backup
rsync $PARAMS $EXCLUDE $SRC $DST
