#!/bin/bash
#requirements:  rsync,  dnf|apt,  figlet

echo "Sync Backup" | figlet

#######################################
#			INITALIZATION
#######################################

#go to source of scripts
SCRIPTS=$HOME/git/bash/syncbackup
cd $SCRIPTS

# Source essential functions
if [ -f "functions.sh" ]; then
		. "functions.sh"
fi

#ubuntu or fedora?
which apt > /dev/null  2>&1
if [ "$?" == "0" ]; then		# probably using ubuntu\debian\mint
	MOUNTEXT=/media
	MOUNT=/mnt
	PKGSYS=apt
else
	which dnf > /dev/null  2>&1
	if [ "$?" == "0" ]; then	# probably using fedora\redhat
		MOUNTEXT=/run/media
		MOUNT=/mnt/
		PKGSYS=dnf
	else
		exit 1
	fi
fi

#rsync missing?
if [ -z `which rsync 2> /dev/null` ]; then		# rsync not installed
		sudo $PKGSYS install rsync
fi

BACKUP="$MOUNT/backup"
BACKUP2="$MOUNTEXT/$USERNAME/BackupExt"
MEDIA="/mnt/media"
WINDOWS="/mnt/win8"

#export variables
export SCRIPTS
export PKGSYS
export BACKUP
export BACKUP2
export MEDIA
export WINDOWS

#######################################
#			   SCRIPTS
#######################################

while [[ ! $continue = "n" ]]; do

	echo -ne "\nSources to backup:
	MEDIA	1
	HOME	2
	SYSTEM	3
	WINDOWS	4
	ALL     5

	Choose: #"
	read script

	case "$script" in
		"1")
		printTitle "MEDIA"
		startScript "$MEDIA" "./000-media/000-media-start" "y"
		;;
		"2")
		printTitle "HOME"
		startScript "$HOME" "./100-home/100-home-start" "y"
		;;
		"3")
		printTitle "SYSTEM"
		startScript "/ (system)" "./200-system/200-system-start" "y"
		;;
		"4")
		printTitle "WINDOWS"
		startScript "$WINDOWS" "./300-win/300-win-start" "y"
		;;
		"5")
		printTitle "MEDIA" && startScript "$MEDIA" "./000-media/000-media-start" "y"
		printTitle "HOME" && startScript "$HOME" "./100-home/100-home-start" "y"
		printTitle "SYSTEM" && startScript "/ (system)" "./200-system/200-system-start" "y"
		printTitle "WINDOWS" && startScript "$WINDOWS" "./300-win/300-win-start" "y"
		;;
		*)
		# no selection

		#umount backup hdd
		umount $BACKUP 2> /dev/null

		#unmount windows hdd
		umount $WINDOWS 2> /dev/null

		exit
	esac

	echo -ne "\n\n\nBackup something else? [y/n]: "
	read continue
	clear

done
