#!/bin/sh

user=`who | grep -m 1 ":1" | cut -d ' ' -f 1`
dbus='export $(cat /proc/$(pgrep -u `whoami` ^gnome-shell$)/environ | grep -z DBUS_SESSION_BUS_ADDRESS)'
cmd='notify-send -i firefox "It has been a week. Time to update firefox"'

su $user -c "$dbus && $cmd"
