#!/bin/bash

if [[ -z $BASE_BKP || -z $SCRIPTS ]]; then
    exit 1
fi

#MOUNT WINDOWS HDD
pkexec mount /mnt/win8 && sleep 5


#######################################
#RSYNC
#######################################
#GO TO RSYNC SCRIPT
cd $SCRIPTS/300-win


#WIN-DOCUMENTS
echo ""
echo -n "Backup win-documents? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./301-win-documents
fi

#WIN-DOCUMENTS-WIN-SW-WIN
echo ""
echo -n "Backup win-downloads-sw-win? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./302-win-downloads-sw-win
fi

#WIN-PICTURES
echo ""
echo -n "Backup win-pictures? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./303-win-pictures
fi

#UNMOUNT WINDOWS HDD
pkexec umount /mnt/win8
