#!/bin/bash
FOLDER_DST="$BASE_BKP/system"

cd $HOME

#MISC
dpkg --get-selections > $FOLDER_DST/package.list

#BACKUP OTHER FOLDERS
sudo tar -pcvzf etc.tar.gz /etc
sudo tar -pcvzf ftp.tar.gz /home/ftp

#MOVE TO EXTERNAL HDD
mv etc.tar.gz $FOLDER_DST/
sudo mv ftp.tar.gz $FOLDER_DST/
