#!/bin/bash

################################################################################
#                                   INIT                                       #
################################################################################
if [[ "$1" = *eclipse*.@(tar.bz2|tar.gz) ]]; then
    FILE=`realpath $1`
fi

RPMEASY=$HOME/git/bash/rpm-scripts/rpmeasy-functions.sh
if [ -f "$RPMEASY" ]; then
        . "$RPMEASY"
fi

prepare_env "eclipse-trunk" \
            "$HOME/git/bash/rpm-scripts/eclipse/eclipse-trunk-skel" \
            "$HOME/git/localrepo"

# move old tar.gz, tar.bz2 or rpm in old folder
mv $DEST/eclipse*.{tar.bz2,tar.gz,rpm} $DEST/old 2> /dev/null

################################################################################
#                                   DOWNLOAD                                   #
################################################################################
URL="http://www.eclipse.org/downloads/?osType=linux"

# download only if custom FILE is not set
if [ -z "$FILE" ]; then
    #open the eclipse downloads page. You need to copy the tar.gg link. It will be used later
    notify-send -i eclipse "Copy link Eclipse IDE for Java Developers(or Java EE) 64bit then close epiphany"
    killall epiphany | sleep 2 && epiphany $URL
    wget `xsel -b` -P $TEMP/src
    FILE=`ls $TEMP/src/*eclipse*.tar.gz`
fi

################################################################################
#                                   SKELETON                                   #
################################################################################
# copy rpm skeleton to $TEMP
cp -rf $SKEL .
# extract the tar.gz then move inside the skeleton
tar -xvzf $FILE -C .

# fix all the things
mv eclipse $PKG_NAME-skel/opt/
cp $SKEL/../extra/splash.bmp $PKG_NAME-skel/opt/eclipse/plugins/org.eclipse.platform*/

################################################################################
#                                   SPEC                                       #
################################################################################
# generate package info
echo "Summary: Eclipse Java Development Tools
Vendor: Eclipse Foundation
Packager: fabiolbr
License: EPL
Group: Applications/Development Tools
URL: http://www.eclipse.org
Description: Eclipse Java Development Tools. This package is required to use Eclipse for developing software written in the Java programming language
#Requires:" > pkg.in

prepare_build jar-repack_off

# fix symbolics links and other conflicts
sed '/^%dir \/usr\/bin$/d' -i *files.txt

################################################################################
#                                BUILD + INSTALL                               #
################################################################################
# build rpm
VERSION=`cat $PKG_NAME-skel/opt/eclipse/configuration/config.ini | grep buildId | cut -d '=' -f 2 | cut -c -5`
RELEASE=`cat $PKG_NAME-skel/opt/eclipse/configuration/config.ini | grep buildId | cut -d '-' -f 1 | cut -c 23-`
#ARCH="x86_64"
build_rpm $VERSION $RELEASE

install_rpm
