#!/bin/bash

################################################################################
#                                   INIT                                       #
################################################################################
RPMEASY=$HOME/git/bash/rpm-scripts/rpmeasy-functions.sh
if [ -f "$RPMEASY" ]; then
        . "$RPMEASY"
fi

prepare_env "eclipse-trunk" \
            "$HOME/git/bash/rpm-scripts/eclipse/eclipse-trunk-skel" \
            "$HOME/git/localrepo"

# move old tar.gz\rpm in old folder
mv $DEST/eclipse*.{tar.gz,rpm} $DEST/old 2> /dev/null

################################################################################
#                                   DOWNLOAD                                   #
################################################################################
URL="http://www.eclipse.org/downloads/?osType=linux"

# download only if there isn't a eclipse-trunk deb package as parameter
if [[ "$1" = *eclipse*.tar.gz ]]; then
    FILE="$1"
else
    #open the eclipse downloads page. You need to copy the tar.gg link. It will be used later
    notify-send -i eclipse "Copy link Eclipse IDE for Java Developers 64bit then close epiphany"
    killall epiphany | sleep 2 && epiphany $URL
    wget `xsel -b` -P $DEST
    FILE=`ls *.tar.gz`
fi

################################################################################
#                                   SKELETON                                   #
################################################################################
# copy rpm skeleton to $TEMP
cp -rf $SKEL .
# extract the tar.gz then move inside the skeleton
tar -xvzf $FILE -C .

# fix all the things
mv eclipse $PKG_NAME-skel/opt/
cp $SKEL/../extra/splash.bmp $PKG_NAME-skel/opt/eclipse/plugins/org.eclipse.platform*/

################################################################################
#                                   SPEC                                       #
################################################################################
# generate package info
echo "Summary: Eclipse Java Development Tools
Vendor: Eclipse Foundation
Packager: fabiolbr
License: EPL
Group: Applications/Development Tools
URL: http://www.eclipse.org
Description: Eclipse Java Development Tools. This package is required to use Eclipse for developing software written in the Java programming language
#Requires:" > pkg.in

prepare_build

# fix symbolics links and other conflicts
sed '/^%dir \/usr\/bin$/d' -i *files.txt
sed 's/%attr(,-,-) \/opt\/eclipse\/plugins\/org.eclipse.recommenders.doc_1.0.5.v20130822-0858-b90\/media\/graffle\/udc-draft (Autosaved).graffle/%attr(664,-,-) \"\/opt\/eclipse\/plugins\/org.eclipse.recommenders.doc_1.0.5.v20130822-0858-b90\/media\/graffle\/udc-draft (Autosaved).graffle\"/g' -i *files.txt

################################################################################
#                                BUILD + INSTALL                               #
################################################################################
# build rpm
VERSION=`cat $PKG_NAME-skel/opt/eclipse/configuration/config.ini | grep buildId | cut -d '=' -f 2 | cut -c -5`
RELEASE=`cat $PKG_NAME-skel/opt/eclipse/configuration/config.ini | grep buildId | cut -d '-' -f 1 | cut -c 23-`
#ARCH="x86_64"
build_rpm $VERSION $RELEASE

install_rpm
