#!/bin/bash

################################################################################
#                                   INIT                                       #
################################################################################
function checkExec () {
    if [ -z `which $1` ]; then
        echo "$1 not present"
        exit
    fi
}

checkExec "rpmwand"

#PKG_NAME=firefox-trunk
PKG_NAME=firefox-aurora
SKEL=$HOME/git/bash/rpm-scripts/firefox/$PKG_NAME-skel  #source of skeleton and script
DEST=$HOME/git/rpm-localrepo  #destination of rpm and tar.bz2
TEMP=/tmp/$PKG_NAME-rpm

mkdir -p $DEST && mkdir -p $TEMP && cd $TEMP

# move old rpm, tar.bz2 in old folder
mv $DEST/firefox*.{tar.bz2,rpm} $DEST/old 2> /dev/null

################################################################################
#                                   DOWNLOAD                                   #
################################################################################
BRANCH=mozilla-aurora
#BRANCH=mozilla-central

VERSION=`curl mxr.mozilla.org/$BRANCH/source/browser/config/version.txt?raw=1\.en-US.linux-x86_64.tar.bz2 -s`
echo "Version: $VERSION"

# download only if there isn't a firefox tar.bz2 package as parameter
if [[ "$1" = *firefox*.tar.bz2 ]]; then
    FILE="$1"  #FIXME: doesn't work with relative path
else
    URL=https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/latest-$BRANCH/firefox-$VERSION.en-US.linux-x86_64.tar.bz2
    echo "Downloading: $URL"
    curl $URL -O -#
    FILE=`ls *.tar.bz2`
fi

################################################################################
#                                   SKELETON                                   #
################################################################################
# copy rpm skeleton to $TEMP
cp -rf $SKEL .
# extract the tar.bz2 then move inside the skeleton
#file-roller --extract-to=$TEMP "$FILE"
tar xf $FILE -C .

# fix all the things
rm -rf firefox/browser/searchplugins
mv firefox $PKG_NAME-skel/usr/lib64/

# create default prefs
mkdir -p $PKG_NAME-skel/usr/lib64/firefox/browser/defaults/preferences
echo -e -n "pref(\"app.update.auto\",                     false);
pref(\"app.update.enabled\",                  false);
pref(\"app.update.autoInstallEnabled\",       false);
pref(\"general.smoothScroll\",                true);
pref(\"intl.locale.matchOS\",                 true);
pref(\"toolkit.storage.synchronous\",         0);
pref(\"toolkit.networkmanager.disable\",      false);
pref(\"offline.autoDetect\",                  true);
pref(\"browser.backspace_action\",            2);
pref(\"browser.display.use_system_colors\",   true);
pref(\"browser.download.folderList\",         1);
pref(\"browser.link.open_external\",          3);
pref(\"browser.shell.checkDefaultBrowser\",   false);
pref(\"network.manage-offline-status\",       true);
pref(\"dom.ipc.plugins.enabled.nswrapper*\",  false);
pref(\"extensions.shownSelectionUI\",         true);
pref(\"gfx.color_management.enablev4\",       true);
pref(\"ui.SpellCheckerUnderlineStyle\",       1);
pref(\"startup.homepage_override_url\",       \"\");
pref(\"browser.startup.homepage\",            \"data:text/plain,browser.startup.homepage=about:newtab\");
pref(\"browser.newtabpage.pinned\",           '[{\"url\":\"http://start.fedoraproject.org/\",\"title\":\"Fedora Project - Start Page\"}]');
" > $PKG_NAME-skel/usr/lib64/firefox/browser/defaults/preferences/firefox-redhat-default-prefs.js

################################################################################
#                                   SPEC                                       #
################################################################################
#initialize and edit *spec.in
rpmwand initspec $PKG_NAME
sed -i 's/Summary: TODO. PLEASE EDIT ME!/Summary: Safe and easy web browser from Mozilla/g'  "$PKG_NAME".spec.in
sed -i 's/Vendor: TODO. PLEASE EDIT ME!/Vendor: Mozilla/g'  "$PKG_NAME".spec.in
sed -i 's/Packager: TODO. PLEASE EDIT ME!/Packager: fabiolbr/g'  "$PKG_NAME".spec.in
sed -i 's/License: TODO. PLEASE EDIT ME!/License: GPL v3/g'  "$PKG_NAME".spec.in
sed -i 's/Group: TODO. PLEASE EDIT ME!/Group: Applications\/Internet/g'  "$PKG_NAME".spec.in
sed -i 's/URL: http:\/\/TODO.example.com\//URL: http:\/\/nightly.mozilla.org/g'  "$PKG_NAME".spec.in
sed -i 's/#Requires:/Requires: mozilla-filesystem sqlite/g' "$PKG_NAME".spec.in

# editing *files.txt and fix conflicts
rpmwand files $PKG_NAME
sed '/^%dir \/usr\/bin$/d' -i "$PKG_NAME"-files.txt
sed '/^%dir \/usr\/lib64$/d' -i "$PKG_NAME"-files.txt

################################################################################
#                                   BUILD                                      #
################################################################################
# build rpm
VERSION=`cat "$PKG_NAME"-skel/usr/lib64/firefox/application.ini | grep Version | cut -d '=' -f 2 | tail -n 1`
RELEASE=`cat "$PKG_NAME"-skel/usr/lib64/firefox/application.ini | grep BuildID | cut -d '=' -f 2`
ARCH="x86_64"
HOME=$TEMP #this force to build inside $TEMP and not $HOME
rpmwand build $PKG_NAME $VERSION $RELEASE $ARCH

################################################################################
#                               INSTALL & CLEANUP                              #
################################################################################
RPM="$TEMP/RPMS/$ARCH/$PKG_NAME-$VERSION-$RELEASE.$ARCH.rpm"

# erase the old package (to avoid unwanted files around the system...)
sudo dnf -y erase $PKG_NAME firefox #remove also the default firefox

# install
sudo dnf -y install $RPM

# save the rpm
cp $RPM $DEST/
# save the tar.bz2
#cp $FILE $DEST/

# cleanup
rm -rf $TEMP
