#!/bin/bash

################################################################################
#                                   INIT                                       #
################################################################################
RPMEASY=$HOME/git/bash/rpm-scripts/rpmeasy-functions.sh
if [ -f "$RPMEASY" ]; then
        . "$RPMEASY"
fi

prepare_env "firefox-daily" \
            "$HOME/git/bash/rpm-scripts/firefox/firefox-daily-skel" \
            "$HOME/git/localrepo" \
            "$1" #FILE

################################################################################
#                                   DOWNLOAD                                   #
################################################################################
if [[ ! -z "$FILE" ]] && [[ "$FILE" = *firefox*.@(tar.bz2|tar.gz) ]]; then
    echo "A file was specified"
elif [[ "$1" = central || "$1" = trunk || "$1" = master || "$1" = nightly ]]; then
    TYPE="firefox-nightly"
    BRANCH="central"
elif [[ "$1" = aurora || "$1" = dev || "$1" = developer || "$1" = devedition ]]; then
    TYPE="firefox-devedition" #TYPE="firefox-aurora"
    BRANCH="beta" #BRANCH="aurora"
elif [[ "$1" = beta ]]; then
    TYPE="firefox-beta"
    BRANCH="beta"
elif [[ "$1" = release || "$1" = firefox ]]; then
    TYPE="firefox"
    BRANCH="release"
else
    echo -e "No branch or file is specified. Default settings will be used\n"
    TYPE="firefox-devedition"
    BRANCH="beta"
fi

if [ -z "$FILE" ]; then

    if [[ "$BRANCH" = central ]]; then
        VERSION=`curl https://hg.mozilla.org/mozilla-$BRANCH/raw-file/tip/browser/config/version.txt -s`
    else
        VERSION=`curl https://hg.mozilla.org/releases/mozilla-$BRANCH/raw-file/tip/browser/config/version.txt -s`
    fi

    echo "TYPE: $TYPE"
    echo "BRANCH: $BRANCH"
    echo "VERSION: $VERSION"
    URL="https://download.mozilla.org/?product=$TYPE-latest&os=linux64&lang=en-US"

    echo "Downloading: $URL"
    curl -L $URL -o "$TYPE-$VERSION.tar.bz2" -#

    FILE=`ls $TEMP/*.tar.bz2`
fi
echo "File: $FILE"

################################################################################
#                                   SKELETON                                   #
################################################################################
# copy rpm skeleton to $TEMP
cp -rf $SKEL .
# extract the tar.bz2 then move inside the skeleton
tar xf $FILE -C .

# fix all the things
rm -rf firefox/browser/searchplugins
mv firefox $PKG_NAME-skel/usr/lib64/$PKG_NAME

# create default prefs
mkdir -p $PKG_NAME-skel/usr/lib64/$PKG_NAME/browser/defaults/preferences
echo -e -n "pref(\"app.update.auto\",                     false);
pref(\"app.update.enabled\",                  false);
pref(\"app.update.autoInstallEnabled\",       false);
pref(\"general.smoothScroll\",                true);
pref(\"intl.locale.matchOS\",                 true);
pref(\"toolkit.storage.synchronous\",         0);
pref(\"toolkit.networkmanager.disable\",      false);
pref(\"offline.autoDetect\",                  true);
pref(\"browser.backspace_action\",            2);
pref(\"browser.display.use_system_colors\",   true);
pref(\"browser.download.folderList\",         1);
pref(\"browser.link.open_external\",          3);
pref(\"browser.shell.checkDefaultBrowser\",   false);
pref(\"network.manage-offline-status\",       true);
pref(\"dom.ipc.plugins.enabled.nswrapper*\",  false);
pref(\"extensions.shownSelectionUI\",         true);
pref(\"gfx.color_management.enablev4\",       true);
pref(\"ui.SpellCheckerUnderlineStyle\",       1);
pref(\"startup.homepage_override_url\",       \"\");
pref(\"browser.startup.homepage\",            \"data:text/plain,browser.startup.homepage=about:newtab\");
pref(\"browser.newtabpage.pinned\",           '[{\"url\":\"http://start.fedoraproject.org/\",\"title\":\"Fedora Project - Start Page\"}]');
" > $PKG_NAME-skel/usr/lib64/$PKG_NAME/browser/defaults/preferences/firefox-redhat-default-prefs.js

################################################################################
#                                   SPEC                                       #
################################################################################
# generate package info
echo "Summary: Safe and easy web browser from Mozilla
Vendor: Mozilla
Packager: fabiolbr
License: GPL v3
Group: Applications/Internet
URL: http://nightly.mozilla.org
Requires: mozilla-filesystem sqlite" > pkg.in

prepare_build

# fix conflicts
sed '/^%dir \/usr\/bin$/d' -i *files.txt
sed '/^%dir \/usr\/lib64$/d' -i *files.txt

################################################################################
#                                BUILD + INSTALL                               #
################################################################################
# build rpm
VERSION=`cat "$PKG_NAME"-skel/usr/lib64/$PKG_NAME/application.ini | grep Version | cut -d '=' -f 2 | tail -n 1`
RELEASE=`cat "$PKG_NAME"-skel/usr/lib64/$PKG_NAME/application.ini | grep BuildID | cut -d '=' -f 2`
#ARCH=`echo $FILE | cut -d '.' -f 3`
build_rpm $VERSION $RELEASE

# move old tar.gz, tar.bz2 or rpm in old folder #TODO: implement inside rpmeasy a new var for "OLD"
mv $DEST/firefox*.{tar.bz2,tar.gz,rpm} $DEST/old 2> /dev/null

# save the tar.bz2 #TODO: use the option inside rpmeasy-functions
cp $FILE $DEST/

install_rpm


