#!/bin/bash

if [[ -z $BACKUP || -z $SCRIPTS ]]; then
	exit 1
fi

# Source essential functions
if [ -f "functions.sh" ]; then
	. "functions.sh"
fi

#mount windows hdd
mount $WINDOWS && sleep 5

#mount backup hdd
mount $BACKUP 2> /dev/null && sleep 3

#######################################
#			   	RSYNC
#######################################

#go to rsync scripts
cd $SCRIPTS/300-win

startScript "$WINDOWS/*/Documents" "./301-win-documents"
startScript "$WINDOWS/*/sw-win" "./302-win-downloads-sw-win"
startScript "$WINDOWS/*/pictures" "./303-win-pictures"
