#!/bin/sh
# take a binary app(must be gtk3) as parameter and it set the dark theme
# "$@" take all the arguments passed to this script

src="$HOME/coding/bash/givemedark"
gtk="$HOME/.config/gtk-3.0"


if [ -z "$@" ]; then
    echo "Usage: givemedark <command> [<arguments>]"
    exit
fi

#backup current settings
cp $gtk/settings.ini $gtk/settings.bak

#force the dark theme
cp $src/settings.dark $gtk/settings.ini

#open the app and all its arguments
"$@"

#take a knee
sleep 1

#restore previous settings
cp $gtk/settings.bak $gtk/settings.ini
