#!/bin/bash

if [[ -z $BASE_BKP || -z $SCRIPTS ]]; then
    exit 1
fi

#######################################
#RSYNC
#######################################
#GO TO RSYNC SCRIPT
cd $SCRIPTS/100-home


#HOME-HIDDEN
echo ""
echo -n "Backup home-hidden? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./101-home-hidden
fi

#HOME-ANDROID
echo ""
echo -n "Backup home-android? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./102-home-android
fi


#HOME-CGI
echo ""
echo -n "Backup home-cgi? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./103-home-cgi
fi


#HOME-DOWNLOADS-SW-LINUX
echo ""
echo -n "Backup home-downloads-sw-linux? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./104-home-downloads-sw-linux
fi


#HOME-DOWNLOADS-OPERATING-SYSTEMS
echo ""
echo -n "Backup home-downloads-operating-systems? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./105-home-downloads-operating-systems
fi


#HOME-VIDEOS
echo ""
echo -n "Backup home-videos? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./106-home-videos
fi


#######################################
#BACKUP OTHER FOLDERS  [tar.gz]
#######################################
FOLDER_DST="$BASE_BKP/home"
cd $HOME

#HOME-WORKSPACE
echo ""
echo -n "Backup home-workspace? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    tar -pcvzf workspace.tar.gz workspace
    mv workspace.tar.gz $FOLDER_DST/
fi


#HOME-DOCUMENTS
echo ""
echo -n "Backup home-documents? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    tar -pcvzf documents.tar.gz documents
    mv documents.tar.gz $FOLDER_DST/
fi

#HOME-CODING
echo ""
echo -n "Backup home-coding? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    tar -pcvzf coding.tar.gz coding
    mv coding.tar.gz $FOLDER_DST/
fi


#HOME-HIDDEN-ANDROID
echo ""
echo -n "Backup home-hidden-android? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    tar -pcvzf hidden_android.tar.gz .android
    mv hidden_android.tar.gz $FOLDER_DST/
fi


#HOME-HIDDEN-SYMLINKS
echo ""
echo -n "Backup home-hidden-symlinks? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
#    tar -pcvzf symlinks.tar.gz ../symlinks --exclude=.cache/thumbnails
#    echo -n "INFO: Excluded   .cache/thumbnails"
    tar -pcvzf symlinks.tar.gz ../symlinks
    mv symlinks.tar.gz $FOLDER_DST/
fi
