#!/bin/bash
#rsync parameters
LOG_FILE="$HOME/.cache/rsync/105-home-downloads-operating-systems.log"
PARAMS=" -r -t -p -o -g -v --progress --delete -l -s -h --stats --log-file=$LOG_FILE"
EXCLUDE=""
SRC="$HOME/downloads/operating-systems/"
DST="/media/fabiolbr/External/home/downloads/operating-systems/"
#NOTE:  the last exclude is basically the name of the dst folder. It's necessary only if dst folder is inside the src folder

#rsynch backup
rsync $PARAMS $EXCLUDE $SRC $DST
