#!/bin/bash

if [[ -z $BACKUP ]]; then
    exit 1
fi

#rsync parameters
LOG_FILE="$HOME/.cache/rsync/002-media-music.log"
PARAMS=" -r -t -p -o -g -v --progress --delete -l -s -h --stats --log-file=$LOG_FILE"
EXCLUDE=""
SRC="$MEDIA/music/"
DST="$BACKUP/media/music/"
#NOTE:  the last exclude is basically the name of the dst folder. It's necessary only if dst folder is inside the src folder

echo ""

#clean trash | it's a mount --bind problem...
rm -rf $SRC.Trash-1000

#rsynch backup
rsync $PARAMS $EXCLUDE $SRC $DST
