#!/bin/bash

if [[ -z $BACKUP ]]; then
    exit 1
fi

#rsync parameters
LOG_FILE="$HOME/.cache/rsync/003-media-tv-shows.log"
PARAMS=" -r -t -p -o -g -v --progress --delete -l -s -h --stats --log-file=$LOG_FILE"
EXCLUDE=""
SRC="$MEDIA/tv-shows/"
DST="$BACKUP/media/tv-shows/"
#NOTE:  the last exclude is basically the name of the dst folder. It's necessary only if dst folder is inside the src folder

echo ""

#rsynch backup
rsync $PARAMS $EXCLUDE $SRC $DST
