#!/bin/bash
#######################################
#RSYNC
#######################################
#GO TO RSYNC SCRIPT
cd $HOME/coding/bash/backup/000-media

#MOVIES
echo ""
echo -n "Backup movies? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./001-media-movies
fi 

#MUSIC
echo ""
echo -n "Backup music? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./002-media-music
fi

#PICTURES
echo ""
echo -n "Backup pictures? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./003-media-pictures
fi

#TV-SHOWS
echo ""
echo -n "Backup tv-shows? (y/n)"
echo ""
read answer
if [[ $answer == "y" ]]; then
    ./004-media-tv-shows
fi


#######################################
#BACKUP OTHER FOLDERS  [tar.gz]
#######################################
FOLDER_SRC="/mnt/media/"
FOLDER_DST="/media/fabiolbr/Backup/media/"
cd $FOLDER_SRC

#XBMC
echo ""
echo -n "Backup .xbmc too? (y/n)"
echo ""
read answer

if [[ $answer == "y" ]]; then
    tar -pcvzf xbmc.tar.gz .xbmc
    mv xbmc.tar.gz  $FOLDER_DST/
fi
