#!/bin/bash

if [[ -z $BASE_BKP ]]; then
    exit 1
fi

#rsync parameters
LOG_FILE="$HOME/.cache/rsync/003-media-pictures.log"
PARAMS=" -r -t -p -o -g -v --progress --delete -l -s -h --stats --log-file=$LOG_FILE"
EXCLUDE=""
SRC="/mnt/media/pictures/"
DST="$BASE_BKP/media/pictures/"
#NOTE:  the last exclude is basically the name of the dst folder. It's necessary only if dst folder is inside the src folder

echo ""
echo "##### BACKUP MEDIA/PICTURES  ##### "

#clean trash | it's a mount --bind problem...
rm -rf $SRC.Trash-1000

#rsynch backup
rsync $PARAMS $EXCLUDE $SRC $DST

